[workspace]
members = ["tls-client", "tls-backend", "tls-core", "prover"]

[workspace.dependencies]
# rand
rand = "0.8"
rand_chacha = "0.3"

# crypto
aes = "0.7"
sha2 = "0.10"
hmac = "0.12"
sct = "0.7"
digest = "0.10"
webpki = "0.22"
ring = "0.16"
elliptic-curve = "0.11"
p256 = "0.10"
ghash_rc = { package = "ghash", version = "0.4" }

# async
async-trait = "0.1"
futures = "0.3"
futures-util = "0.3"
tokio = "1.23"
tokio-util = "0.7"

# num
num = "0.4"
num-bigint = "0.4"
num-traits = "0.2"

# serialization
serde = "1.0"
prost = "0.9"
prost-build = "0.9"

# error/log
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1"

# testing
criterion = "0.3"

# misc
regex = "1"
rayon = "1"
hex = "0.4"
once_cell = "1"
generic-array = "0.14"
