[package]
name = "pop-mpc-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9"

[build-dependencies]
prost-build = "0.9"