[package]
name = "tests-integration"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
tlsn-tls-core.workspace = true
tlsn-prover = { workspace = true, features = ["formats"] }
tlsn-notary.workspace = true
tlsn-server-fixture.workspace = true

p256 = { workspace = true, features = ["ecdsa"] }
hyper = { workspace = true, features = ["client", "http1"] }

futures.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tokio-util.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

serde_json = "1.0"
bincode = "*"

[[test]]
name = "http"
