[package]
name = "tlsn-tls-backend"
authors = ["TLSNotary Team"]
description = "A TLS backend trait for TLSNotary"
keywords = ["tls", "mpc", "2pc"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.6"
edition = "2021"

[lib]
name = "tls_backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tlsn-tls-core = { path = "../tls-core" }
async-trait.workspace = true
thiserror.workspace = true
futures.workspace = true
