[package]
name = "tlsn-hmac-sha256-utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "hmac_sha256_utils"

[dependencies]
hmac.workspace = true
sha2 = { workspace = true, features = ["compress"] }
