[package]
name = "tlsn-mpc-garble-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpc_garble_core"

[profile.release]
lto = true

[dependencies]
tlsn-mpc-core.workspace = true
tlsn-mpc-circuits.workspace = true
tlsn-utils.workspace = true

aes = { workspace = true, features = [] }
cipher.workspace = true
blake3.workspace = true
rand.workspace = true
rand_core.workspace = true
rand_chacha.workspace = true
regex = { workspace = true, optional = true }

serde = { workspace = true, features = ["derive"] }
serde_arrays.workspace = true
thiserror.workspace = true
derive_builder.workspace = true

[dev-dependencies]
rstest.workspace = true
criterion.workspace = true
pretty_assertions.workspace = true

[[bench]]
name = "garble"
harness = false

[[bench]]
name = "encoder"
harness = false
