[package]
name = "tlsn-tls-mpc"
version = "0.1.0"
edition = "2021"

[lib]
name = "tls_mpc"

[dependencies]
tlsn-tls-core = { path = "../tls-core", features = ["serde"] }
tlsn-tls-backend = { path = "../tls-backend" }

tlsn-mpc-core = { git = "https://github.com/tlsnotary/mpz" }
tlsn-mpc-garble = { git = "https://github.com/tlsnotary/mpz" }
tlsn-mpc-ot = { git = "https://github.com/tlsnotary/mpz" }
tlsn-mpc-share-conversion = { git = "https://github.com/tlsnotary/mpz" }
tlsn-block-cipher = { path = "../../cipher/block-cipher" }
tlsn-stream-cipher = { path = "../../cipher/stream-cipher" }
tlsn-universal-hash = { path = "../../universal-hash" }
tlsn-aead = { path = "../../aead" }
tlsn-key-exchange = { path = "../../key-exchange" }
tlsn-point-addition = { path = "../../point-addition" }
tlsn-hmac-sha256 = { path = "../../prf/hmac-sha256" }
tlsn-utils = { git = "https://github.com/tlsnotary/tlsn-utils" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils" }

p256 = { version = "0.12" }

rand.workspace = true

futures.workspace = true
async-trait.workspace = true

serde.workspace = true
derive_builder.workspace = true
thiserror.workspace = true

[dev-dependencies]
tlsn-tls-client = { path = "../tls-client" }
tlsn-tls-client-async = { path = "../tls-client-async" }
tls-server-fixture = { path = "../tls-server-fixture" }
actor-ot = { path = "../../actors/actor-ot" }
uid-mux = { path = "../../uid-mux" }

webpki-roots = "0.22"

tokio = { version = "1.23", features = ["macros", "rt", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["compat"] }
