[package]
name = "tlsn-formats"
version = "0.1.0-alpha.12-pre"
edition = "2021"

[lints]
workspace = true

[dependencies]
tlsn-core = { workspace = true }

bytes = { workspace = true }
spansy = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }

[dev-dependencies]
tlsn-core = { workspace = true, features = ["fixtures"] }
tlsn-data-fixtures = { workspace = true }
rstest = { workspace = true }
