[workspace]
members = ["hmac-sha256-circuits", "hmac-sha256"]
resolver = "2"

[workspace.dependencies]
# tlsn
<<<<<<< HEAD
mpz-circuits = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }
mpz-garble = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }

# async
async-trait = "0.1"
futures = "0.3"
tokio = "1"

# error/log
thiserror = "1"
tracing = "0.1"

# testing
criterion = "0.5"
