[package]
name = "tlsn-universal-hash"
authors = ["TLSNotary Team"]
description ="A crate which implements different hash functions for two-party computation"
keywords = ["tls", "mpc", "2pc", "hash"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = ["ghash", "mock"]
tracing = ["dep:tracing"]
ghash = []
mock = []

[dependencies]
# tlsn
tlsn-mpc-core = { path = "../mpc/mpc-core" }
tlsn-mpc-share-conversion-core = { path = "../mpc/share-conversion/mpc-share-conversion-core" }
tlsn-mpc-share-conversion = { path = "../mpc/share-conversion/mpc-share-conversion" }

# async
async-trait = "0.1"
futures = "0.3"
futures-util = "0.3"

# error/log
thiserror = "1"
opaque-debug = "0.3"
tracing = {version = "0.1", optional = true}

# misc
derive_builder = "0.12"

[dev-dependencies]
ghash_rc = { package = "ghash", version = "0.5" }
tokio = "1"
criterion = "0.5"
rstest = "0.17"
rand_chacha = "0.3"
rand = "0.8"
generic-array = "0.14"

