[package]
name = "tlsn-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tlsn-mpc-core.workspace = true
tlsn-mpc-garble-core.workspace = true
tlsn-mpc-circuits.workspace = true
tlsn-utils.workspace = true

thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
p256 = { version = "0.10", features = ["ecdsa", "serde", "sha256"] }
webpki = { version = "0.22.0", features = ["alloc"] }
webpki-roots = "0.22.5"
x509-parser = "0.14.0"
blake3 = "1.3.3"
rs_merkle = "1.2.0"
rand_chacha = "0.3"
rand = "0.8"
rand_core = "0.6"

[dev-dependencies]
rstest = "0.12"
hex = "0.4"
bcs = "0.1.5"
