[package]
name = "tlsn-core"
version = "0.1.0"
edition = "2021"

[features]
default = []
fixtures = ["dep:rstest", "dep:hex"]

[dependencies]
tlsn-tls-core = { workspace = true, features = ["serde"] }
tlsn-mpc-core.workspace = true
tlsn-mpc-garble-core.workspace = true
tlsn-mpc-circuits.workspace = true
tlsn-utils.workspace = true

thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
p256 = { version = "0.10", features = ["ecdsa", "serde", "sha256"] }
webpki = { version = "0.22.0", features = ["alloc"] }
webpki-roots = "0.22.5"
x509-parser = "0.14.0"
blake3 = "1.3.3"
rs_merkle = "1.2.0"
rand_chacha = "0.3"
rand = "0.8"
rand_core = "0.6"

rstest = { version = "0.12", optional = true }
hex = { version = "0.4", optional = true }

[dev-dependencies]
rstest = "0.12"
hex = "0.4"
bcs = "0.1.5"

[[test]]
name = "api"
required-features = ["fixtures"]
