[package]
name = "tlsn-core"
authors = ["TLSNotary Team"]
description = "Core types for TLSNotary"
keywords = ["tls", "mpc", "2pc", "types"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = []
fixtures = ["dep:hex"]
tracing = ["dep:tracing"]

[dependencies]
tlsn-tls-core = { workspace = true, features = ["serde"] }

tlsn-utils.workspace = true

mpz-core.workspace = true
mpz-garble-core.workspace = true
mpz-circuits.workspace = true

thiserror.workspace = true
serde.workspace = true
p256 = { workspace = true, features = ["serde"] }
webpki-roots.workspace = true
rs_merkle.workspace = true
rstest = { workspace = true, optional = true}
hex = { workspace = true, optional = true} 
tracing = { workspace = true, optional = true }

[dev-dependencies]
rstest.workspace = true
hex.workspace = true
rand_core.workspace = true
rand_chacha.workspace = true
bincode.workspace = true

[[test]]
name = "api"
required-features = ["fixtures"]
