[package]
edition = "2021"
name = "tlsn-benches-browser-native"
publish = false
version = "0.0.0"

[lints]
workspace = true

[dependencies]
tlsn-benches-browser-core = { workspace = true }
tlsn-benches-library = { workspace = true }

serio = { workspace = true }
websocket-relay = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
chromiumoxide = { version = "0.6.0" , features = ["tokio-runtime"] }
futures = { workspace = true }
rust-embed = "8.5.0"
tokio = { workspace = true, features = ["rt", "io-std"] }
tracing = { workspace = true }
warp = "0.3.7"
warp-embed = "0.5.0"
