[package]
edition = "2021"
name = "tlsn-benches-browser-native"
publish = false
version = "0.1.0"

[dependencies]
tlsn-benches-browser-core = { workspace = true }
tlsn-benches-library = { workspace = true }

serio = { workspace = true }
websocket-relay = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "76c9de0" }

anyhow = { workspace = true }
async-trait = { workspace = true }
chromiumoxide = { version = "0.6.0" , features = ["tokio-runtime"] }
futures = { workspace = true }
rust-embed = "8.5.0"
tokio = { workspace = true, features = ["rt", "io-std"] }
tokio-tungstenite = { version = "0.23", features = ["url"] }
tracing = { workspace = true }
warp = "0.3.7"
warp-embed = "0.5.0"
