[package]
name = "tlsn-harness-plot"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
tlsn-harness-core = { workspace = true }
# tlsn-server-fixture = { workspace = true }
charming = { version = "0.6.0", features = ["ssr"] }
clap = { workspace = true, features = ["derive", "env"] }
polars = { version = "0.44", features = ["csv", "lazy"] }
toml = { workspace = true }


[[bin]]
name = "tlsn-harness-plot"
path = "bin/plot.rs"
