[package]
name = "tlsn-utils-aio"
version = "0.1.0"
edition = "2021"

[lib]
name = "utils_aio"

[features]
default = []
codec = []
mux = []
duplex = []

[dependencies]
bytes.workspace = true
prost.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }
async-tungstenite.workspace = true
futures.workspace = true
futures-util.workspace = true
async-trait.workspace = true
yamux.workspace = true
thiserror.workspace = true
async-std.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "io-util",
    "time",
] }
