[package]
name = "tlsn-plugin-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tlsn = { workspace = true }
tlsn-core = { workspace = true }
tlsn-formats = { workspace = true }

http-body-util = { workspace = true }
hyper = { workspace = true, features = ["client", "http1"] }
rangeset = { workspace = true }
serde = { workspace = true }
spansy = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tlsn-data-fixtures = { workspace = true }

[lints]
workspace = true
