[package]
name = "tlsn-tls-core"
version = "0.1.0"
edition = "2018"

[lib]
name = "tls_core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["prf", "ghash"]
prf = []
ghash = []

[dependencies]
tlsn-mpc-core = { path = "../mpc-core" }
sha2 = { version = "0.10.1", features = ["compress"] }
digest = { version = "0.10.3" }
hmac = { version = "0.12.1" }
rand = "0.8.5"
thiserror = "1.0.30"

[dev-dependencies]
criterion = "0.3.5"
ghash_rc = { package = "ghash", version = "0.4.4" }
rand_chacha = "0.3.1"
