[package]
name = "tlsn-mpc-circuits-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpc_circuits_macros"
proc-macro = true

[dependencies]
syn = { version = "1", features = [
    "full",
    "extra-traits",
    "visit-mut",
    "visit",
] }
quote = "1"
proc-macro2 = "1"
