[package]
name = "tlsn-hmac-sha256"
authors = ["TLSNotary Team"]
description = "A 2PC implementation of TLS HMAC-SHA256 PRF"
keywords = ["tls", "mpc", "2pc", "hmac", "sha256"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.2"
edition = "2021"

[lib]
name = "hmac_sha256"

[features]
default = ["mock"]
tracing = ["dep:tracing", "tlsn-hmac-sha256-circuits/tracing"]
mock = []

[dependencies]
tlsn-hmac-sha256-circuits = { path = "../hmac-sha256-circuits" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "8d8ffe1" }
mpz-garble.workspace = true
mpz-circuits.workspace = true

async-trait.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }
derive_builder = "0.12"
enum-try-as-inner = "0.1"

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[[bench]]
name = "prf"
harness = false
