[package]
name = "tlsn-tls-client-async"
authors = ["TLSNotary Team"]
description = "An async TLS client for TLSNotary"
keywords = ["tls", "mpc", "2pc", "client", "async"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.6"
edition = "2021"

[lib]
name = "tls_client_async"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
tlsn-tls-client = { path = "../tls-client" }
bytes.workspace = true
futures.workspace = true
tokio-util = { workspace = true, features = ["io", "compat"] }
tracing = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
webpki-roots.workspace = true
hyper = { workspace = true, features = ["client", "http1"] }
tls-server-fixture = { path = "../tls-server-fixture" }
rstest = { workspace = true }
http-body-util.workspace = true
hyper-util = { workspace = true, features = ["full"] }
