[package]
name = "tlsn-verifier"
authors = ["TLSNotary Team"]
description = "A library for the TLSNotary verifier"
keywords = ["tls", "mpc", "2pc"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.2"
edition = "2021"

[features]
tracing = ["dep:tracing", "tlsn-tls-mpc/tracing"]

[dependencies]
tlsn-core.workspace = true
tlsn-tls-core.workspace = true
tlsn-tls-mpc.workspace = true
uid-mux.workspace = true

tlsn-utils-aio.workspace = true

mpz-core.workspace = true
mpz-garble.workspace = true
mpz-ot.workspace = true
mpz-share-conversion.workspace = true

futures.workspace = true
thiserror.workspace = true
derive_builder.workspace = true
rand.workspace = true
signature.workspace = true
opaque-debug.workspace = true

tracing = { workspace = true, optional = true }
