#### Bandwidth ####

[[group]]
name = "bandwidth"
protocol_latency = 25

[[bench]]
group = "bandwidth"
bandwidth = 10

[[bench]]
group = "bandwidth"
bandwidth = 50

[[bench]]
group = "bandwidth"
bandwidth = 100

[[bench]]
group = "bandwidth"
bandwidth = 250

[[bench]]
group = "bandwidth"
bandwidth = 1000
