[package]
name = "notary-server"
version = "0.1.0-alpha.9-pre"
edition = "2021"

[features]
default = ["tee_quote"]
tee_quote = [
	"dep:mc-sgx-dcap-types",
	"dep:hex",
	"dep:rand",
	"dep:rand06-compat",
	"dep:once_cell",
	"dep:simple_asn1",
	"dep:pem",
	"dep:lazy_static",
]

[dependencies]
tlsn-core = { workspace = true }
tlsn-common = { workspace = true }
tlsn-verifier = { workspace = true }

async-tungstenite = { workspace = true, features = ["tokio-native-tls"] }
axum = { workspace = true, features = ["ws"] }
axum-core = { version = "0.5" }
axum-macros = { version = "0.5" }
base64 = { version = "0.21" }
config = { version = "0.14", features = ["yaml"] }
csv = { version = "1.3" }
eyre = { version = "0.6" }
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["client", "http1", "server"] }
hyper-util = { workspace = true, features = ["full"] }
k256 = { workspace = true }
notify = { version = "6.1.1", default-features = false, features = [
	"macos_kqueue",
] }
p256 = { workspace = true }
pkcs8 = { workspace = true, features = ["pem"] }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { version = "0.9" }
sha1 = { version = "0.10" }
structopt = { version = "0.3" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true, features = ["compat"] }
tower-http = { version = "0.5", features = ["cors"] }
tower-service = { version = "0.3" }
tower-util = { version = "0.3.1" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4", "fast-rng"] }
ws_stream_tungstenite = { workspace = true, features = ["tokio_io"] }
zeroize = { workspace = true }

mc-sgx-dcap-types = { version = "0.11.0", optional = true }
hex = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
rand06-compat = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
simple_asn1 = { version = "0.6.2", optional = true }
pem = { version = "1.1.0", optional = true }
lazy_static = { version = "1.4", optional = true }

[build-dependencies]
git2 = "0.19.0"
chrono.workspace = true
