[package]
name = "actor-ot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpz-ot-core = { git = "https://github.com/tlsnotary/mpz" }
mpz-ot = { git = "https://github.com/tlsnotary/mpz" }
mpz-core = { git = "https://github.com/tlsnotary/mpz" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils" }
async-trait = "0.1"
derive_builder = "0.11"
futures = "0.3"
thiserror = "1"
xtra = { git = "https://github.com/Restioson/xtra", rev = "ca061b4", features = [
    "macros",
], default-features = false }

[features]
default = ["mock"]
mock = []


[dev-dependencies]
xtra = { git = "https://github.com/Restioson/xtra", rev = "ca061b4", features = [
    "tokio",
], default-features = false }
tokio = { version = "1.23", features = [
    "macros",
    "io-util",
    "rt",
    "rt-multi-thread",
] }
