[package]
name = "tlsn-tls-2pc-aio"
version = "0.1.0"
edition = "2021"

[lib]
name = "tls_2pc_aio"

[features]
default = ["mock"]
mock = ["dep:share-conversion-core", "dep:rand_chacha", "dep:rand"]

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
tlsn-tls-2pc-core = { path = "../tls-2pc-core" }
share-conversion-aio = { path = "../../mpc/share-conversion-aio" }
share-conversion-core = { path = "../../mpc/share-conversion-core", optional = true }
rand_chacha = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true
ghash_rc.workspace = true

# [[bench]]
# name = "prf"
# harness = false
