[package]
name = "tlsn-key-exchange"
authors = ["TLSNotary Team"]
description = "Implementation of the TLSNotary-specific key-exchange protocol"
keywords = ["tls", "mpc", "2pc", "pms", "key-exchange"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.2"
edition = "2021"

[lib]
name = "key_exchange"

[features]
default = ["mock"]
tracing = ["dep:tracing", "tlsn-point-addition/tracing"]
mock = []

[dependencies]
mpz-garble = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "1ac6779" }
mpz-ot = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "1ac6779" }
mpz-circuits = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "1ac6779" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "8d8ffe1" }
mpz-share-conversion-core = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "1ac6779" }
tlsn-point-addition = { path = "../point-addition" }
p256 = { version = "0.13", features = ["ecdh"] }
async-trait = "0.1"
thiserror = "1"
serde = "1"
futures = "0.3"
derive_builder = "0.12"
tracing = { version = "0.1", optional = true }

[dev-dependencies]
rand_chacha = "0.3"
rand_core = "0.6"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
