[package]
edition = "2021"
name = "tlsn-examples"
publish = false
version = "0.0.0"

[dependencies]
actix-web = "4.0"
mpz-core.workspace = true
notary-server = {path = "../../notary-server"}
tlsn-core.workspace = true
tlsn-prover = {workspace = true, features = ["tracing"]}
tlsn-tls-client.workspace = true
tlsn-tls-core.workspace = true
tlsn-utils.workspace = true
tlsn-verifier.workspace = true

elliptic-curve = {version = "0.13.5", features = ["pkcs8"]}
p256 = {workspace = true, features = ["ecdsa"]}
webpki-roots.workspace = true

async-tls = {version = "0.12", default-features = false, features = [
  "client",
]}
chrono = "0.4"
futures.workspace = true
http-body-util = "0.1"
hyper = {version = "1.3.1", features = ["client", "http1"]}
hyper-util = {version = "0.1", features = ["full"]}
rustls = {version = "0.21"}
rustls-pemfile = {version = "1.0.2"}
tokio = {workspace = true, features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "net",
  "io-std",
  "fs",
]}
tokio-rustls = {version = "0.24.1"}
tokio-util.workspace = true

dotenv = "0.15.0"
eyre = "0.6.8"
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0"
tracing-subscriber.workspace = true
tracing.workspace = true

regex = "1.10.3"
reqwest = "0.12.5"

[[example]]
name = "simple_prover"
path = "simple/simple_prover.rs"

[[example]]
name = "simple_verifier"
path = "simple/simple_verifier.rs"

[[example]]
name = "twitter_dm"
path = "twitter/twitter_dm.rs"

[[example]]
name = "discord_dm"
path = "discord/discord_dm.rs"

[[example]]
name = "discord_dm_verifier"
path = "discord/discord_dm_verifier.rs"

[[example]]
name = "interactive"
path = "interactive/interactive.rs"

[[example]]
name = "pawa"
path = "pawa/pawa.rs"
