[package]
edition = "2021"
name = "tlsn-examples"
publish = false
version = "0.0.0"

[dependencies]
notary-client.workspace = true
tlsn-core.workspace = true
tlsn-prover = { workspace = true }
tlsn-verifier.workspace = true

futures.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["client", "http1"] }
hyper-util = { workspace = true, features = ["full"] }
p256 = { workspace = true, features = ["ecdsa"] }
tokio = { workspace = true, features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "net",
  "io-std",
  "fs",
] }
tokio-util.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
mpz-core.workspace = true
chrono = "0.4"
dotenv = "0.15.0"
elliptic-curve = { version = "0.13.5", features = ["pkcs8"] }
regex = "1.10.3"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] } 
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

[[example]]
name = "simple_prover"
path = "simple/simple_prover.rs"

[[example]]
name = "simple_verifier"
path = "simple/simple_verifier.rs"

[[example]]
name = "twitter_dm"
path = "twitter/twitter_dm.rs"

[[example]]
name = "discord_dm"
path = "discord/discord_dm.rs"

[[example]]
name = "discord_dm_verifier"
path = "discord/discord_dm_verifier.rs"

[[example]]
name = "interactive"
path = "interactive/interactive.rs"

[[example]]
name = "binance_prover"
path = "binance/binance_prover.rs"

[[example]]
name = "binance_verifier"
path = "binance/binance_verifier.rs"
