[workspace]
members = [
    "tlsn-core",
    "tlsn-notary",
    "tlsn-prover",
    "tests-integration",
    "examples",
]
resolver = "2"

[workspace.dependencies]
tlsn-core = { path = "tlsn-core" }
tlsn-prover = { path = "tlsn-prover" }
tlsn-notary = { path = "tlsn-notary" }

tlsn-tls-core = { path = "../components/tls/tls-core" }
tlsn-tls-mpc = { path = "../components/tls/tls-mpc" }
tlsn-tls-client = { path = "../components/tls/tls-client" }
tlsn-tls-client-async = { path = "../components/tls/tls-client-async" }
tls-server-fixture = { path = "../components/tls/tls-server-fixture" }
uid-mux = { path = "../components/uid-mux" }

tlsn-utils = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "b182066" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "b182066" }

mpz-core = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "76ed767" }
mpz-circuits = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "76ed767" }
mpz-garble-core = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "76ed767" }
mpz-garble = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "76ed767" }
mpz-ot = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "76ed767" }
mpz-share-conversion = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "76ed767" }


futures = "0.3"
tokio-util = "0.7"
hyper = "<=0.14.26"
tokio = "1"

signature = "2"
p256 = "0.13"
rs_merkle = "1"
rand_chacha = "0.3"
rand = "0.8"
rand_core = "0.6"
webpki-roots = "0.23"

derive_builder = "0.12"
thiserror = "1"
serde = "1"
bincode = "1"
hex = "0.4"
bytes = "1.4"
opaque-debug = "0.3"

tracing = "0.1"
tracing-subscriber = "0.3"
rstest = "0.17"
