[workspace]
members = [
    "tlsn-core",
    "tlsn-notary",
    "tlsn-prover",
    "tests-integration",
    "examples",
]

[workspace.dependencies]
tlsn-core = { path = "tlsn-core" }
tlsn-prover = { path = "tlsn-prover" }
tlsn-notary = { path = "tlsn-notary" }

tlsn-tls-core = { path = "../components/tls/tls-core" }
tlsn-tls-mpc = { path = "../components/tls/tls-mpc" }
tlsn-tls-client = { path = "../components/tls/tls-client" }
tlsn-tls-client-async = { path = "../components/tls/tls-client-async" }
tls-server-fixture = { path = "../components/tls/tls-server-fixture" }

mpz-core = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }
mpz-circuits = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }
mpz-garble-core = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }
mpz-garble = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }
tlsn-utils = { git = "https://github.com/tlsnotary/tlsn-utils" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils" }
mpz-share-conversion = { git = "https://github.com/tlsnotary/mpz", rev = "5a66465" }

actor-ot = { path = "../components/actors/actor-ot" }

uid-mux = { path = "../components/uid-mux" }

futures = "0.3"
tokio-util = { version = "0.7", features = ["compat"] }

rand = "0.8"
signature = "2.0"
p256 = "0.13"

derive_builder = "0.11"
thiserror = "1"

bytes = "1"

tokio = "1.23"
webpki-roots = "0.23"

tracing = "0.1"
tracing-subscriber = "0.3"
