[workspace]
members = ["tlsn-core", "tlsn-notary", "tlsn-prover", "tests-integration"]

[workspace.dependencies]
tlsn-core = { path = "tlsn-core" }
tlsn-prover = { path = "tlsn-prover" }
tlsn-notary = { path = "tlsn-notary" }

tlsn-tls-core = { path = "../tls/tls-core" }
tlsn-tls-mpc = { path = "../tls/tls-mpc" }
tlsn-tls-client = { path = "../tls/tls-client" }

tlsn-mpc-core = { path = "../mpc/mpc-core" }
tlsn-mpc-circuits = { path = "../mpc/mpc-circuits" }
tlsn-mpc-garble-core = { path = "../mpc/garble/mpc-garble-core" }
tlsn-mpc-garble = { path = "../mpc/garble/mpc-garble" }
tlsn-utils = { path = "../utils/utils" }
tlsn-utils-aio = { path = "../utils/utils-aio" }
tlsn-mpc-share-conversion = { path = "../mpc/share-conversion/mpc-share-conversion" }

actor-ot = { path = "../actors/actor-ot" }

uid-mux = { path = "../uid-mux" }

futures = "0.3"
tokio-util = { version = "0.7", features = ["compat"] }

rand = "0.8"
signature = "2.0"
p256 = "0.13"

derive_builder = "0.11"
thiserror = "1"

bytes = "1"

tokio = "1.23"
webpki-roots = "0.23"
